name = "SeisTimes"
uuid = "5046edd9-8c47-4906-87d4-c35907f4bba7"
authors = ["wtegtow <w.tegtow@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
